apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - volumes
  - shared
  - todo-backend
  - todo
  - cronjobs

images:
  - name: waltherbeach/todo
    newName: waltherbeach/todo
    newTag: 26-01-10
  - name: waltherbeach/todo-backend
    newName: waltherbeach/todo-backend
    newTag: 26-01-6
