apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: hashgenerator-svc
spec:
  type: NodePort
  selector:
    app: hashgenerator
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5001
