apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: exercises
  name: pingpong-route
spec:
  parentRefs:
  - name: log-output-gateway
    namespace: exercises
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
    backendRefs:
    - name: pingpong-svc
      port: 80
