apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: cache-claim
spec:
  storageClassName: shared-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
