apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: project
  name: todo-route
spec:
  parentRefs:
    - name: todo-gateway
      namespace: project
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: todo-svc
          port: 80
