apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: random-wiki-todo-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: random-wiki
              image: curlimages/curl
              env:
                - name: WIKI_RANDOM_URL
                  value: "https://en.wikipedia.org/wiki/Special:Random"
                - name: TODO_BACKEND_URL
                  value: "http://todo-backend-svc:80/todos"
              command:
                - /bin/sh
                - -c
                - |
                  TARGET_URL=$(curl -Is "$WIKI_RANDOM_URL" | grep -i '^location:' | awk '{print $2}' | tr -d '\r')

                  if [ -z "$TARGET_URL" ]; then
                    echo "Error: Could not retrieve redirect URL"
                    exit 1
                  fi

                  echo "Captured URL: $TARGET_URL"

                  curl -X POST "$TODO_BACKEND_URL" \
                    -H "Content-Type: application/json" \
                    -d "{\"content\": \"Read $TARGET_URL\"}"
          restartPolicy: OnFailure
