name: Build and Deploy to GKE

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: k8s-course
  CLUSTER_NAME: dwk-cluster
  CLUSTER_ZONE: europe-north1-b

jobs:
  setup-build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Full Image Names
        run: |
          TAG=${{ github.sha }}
          BASE_URL=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}

          echo "TODO_IMAGE=$BASE_URL/todo:$TAG" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$BASE_URL/todo-backend:$TAG" >> $GITHUB_ENV

      - name: Authenticate Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Todo
        uses: docker/build-push-action@v5
        with:
          context: ./the_project/apps/todo
          platforms: linux/amd64
          push: true
          tags: ${{ env.TODO_IMAGE }}

      - name: Build and Push Todo Backend
        uses: docker/build-push-action@v5
        with:
          context: ./the_project/apps/todo-backend
          platforms: linux/amd64
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      - name: Update Kustomize Image Tags
        run: |-
          cd manifests
          kustomize edit set image waltherbeach/todo=${{ env.TODO_IMAGE }}
          kustomize edit set image waltherbeach/todo-backend=${{ env.BACKEND_IMAGE }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Deploy and Verify
        run: |-
          kubectl apply -k manifests

          echo "Verifying Rollouts..."
          kubectl rollout status deployment/todo-dep -n project --timeout=300s
          kubectl rollout status deployment/todo-backend-dep -n project --timeout=120s

          echo "Deployment complete. Current Services:"
          kubectl get services -n project -o wide
          echo "Waiting for Gateway"
          kubectl wait --for=jsonpath='{.status.addresses[0].value}' gateway/todo-gateway -n project --timeout=120s
          echo "Gateway Status"
          kubectl get gateway -n project
