name: Build and Deploy to GKE

on:
  push:
    branches: ["**"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: k8s-course
  CLUSTER_NAME: dwk-cluster
  CLUSTER_ZONE: europe-north1-b
  BACKUP_BUCKET: todo-postgres-backups-20260128

jobs:
  setup-build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Namespace
        id: get-ns
        uses: ./.github/actions/get-namespace

      - name: Set Dynamic Environment Variables
        run: |
          NAMESPACE=${{ steps.get-ns.outputs.namespace }}
          echo "K8S_NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set Full Image Names
        run: |
          TAG="${{ env.K8S_NAMESPACE }}-${{ github.sha }}"
          BASE_URL=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}

          echo "TODO_IMAGE=$BASE_URL/todo:$TAG" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$BASE_URL/todo-backend:$TAG" >> $GITHUB_ENV
          echo "BACKUP_IMAGE=$BASE_URL/todo-backup:$TAG" >> $GITHUB_ENV

      - name: Authenticate Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Images
        uses: docker/bake-action@v5
        with:
          push: true
          workdir: ./the_project
          files: docker-compose.build.yaml
          set: |
            todo.tags=${{ env.TODO_IMAGE }}
            backend.tags=${{ env.BACKEND_IMAGE }}
            backup.tags=${{ env.BACKUP_IMAGE }}

      - name: Update Kustomize Manifests
        run: |-
          cd manifests
          sed -i "s/\${PROJECT_ID}/${{ env.PROJECT_ID }}/g" kustomization.yaml
          kustomize edit set namespace ${{ env.K8S_NAMESPACE }}
          kustomize edit set image waltherbeach/todo=${{ env.TODO_IMAGE }}
          kustomize edit set image waltherbeach/todo-backend=${{ env.BACKEND_IMAGE }}
          kustomize edit set image waltherbeach/todo-backup=${{ env.BACKUP_IMAGE }}

      - name: Authorize Workload Identity
        run: |
          gcloud iam service-accounts add-iam-policy-binding pg-backup-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --role="roles/iam.workloadIdentityUser" \
            --member="serviceAccount:${{ env.PROJECT_ID }}.svc.id.goog[${{ env.K8S_NAMESPACE }}/todo-backup-sa]"

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Prepare Namespace
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace ${{ env.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

          # Set the namespace
          kubectl config set-context --current --namespace=${{ env.K8S_NAMESPACE }}

          # Create the database secret in the namespace if it doesn't exist
          kubectl create secret generic todo-db-secret \
            --namespace=${{ env.K8S_NAMESPACE }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy and Verify
        run: |-
          kubectl apply -k manifests -n ${{ env.K8S_NAMESPACE }}

          echo "Verifying Rollouts in namespace: ${{ env.K8S_NAMESPACE }}..."
          kubectl rollout status deployment/todo-dep --timeout=300s
          kubectl rollout status deployment/todo-backend-dep --timeout=120s

          echo "Deployment complete. Current Services:"
          kubectl get services -o wide

          echo "Waiting for Gateway"
          kubectl wait --for=jsonpath='{.status.addresses[0].value}' gateway/todo-gateway --timeout=120s

          echo "Gateway Status"
          kubectl get gateway
